### PR TITLE
Add (preliminary) support for ethernet control of Jaco arms

### PR DESCRIPTION
**Pull request by sammy-tri**

### CODE REVIEW

**Comment by calderpg-tri** [comment]
USB/Ethernet switching is being handled in much the same way we handle ROS1/ROS2 build switching, so I don't think it's too bad of a hack. I would say that `MAYBE_ETHERNET(Function(args))` does look a bit odd, and I'd generally say macros that look function-like but aren't are potentially confusing. Based on what we did with the ROS1/ROS2 handling, would it be better to do something like
```
#ifdef USE_ETHERNET
  using SdkGetAngularPosition = Ethernet_GetAngularPosition;
#else
  using SdkGetAngularPosition = GetAngularPosition;
#endif
```
so that USB/Ethernet-specific switches all occur in one place and then there aren't macro invocations all over?

**Comment by sammy-tri** [comment]
Does 'using' work for free functions?  It doesn't appear to...

**Comment by calderpg-tri** [comment]
I didn't remember if `using` would work for that. In that case
```
#ifdef USE_ETHERNET
  #define SdkGetAngularPosition Ethernet_GetAngularPosition
#else
  #define SdkGetAngularPosition GetAngularPosition
#endif
```
would work instead.

**Comment by sammy-tri** [comment]
Tried something similar to your suggestion.   Surprisingly (to me) the preprocessor/compiler really wanted me to use macros with arguments.

**Pull request merged**
